### ISSUE TITLE
Create Level 0 Diagram

### ISSUE THREAD

**Issue by alychow** [alychow/FinPop-MIE350#6]

**Comment by jappyaid** [comment]
So this is a level 0 for each function? Now that we learned it today I can probs do it

**Comment by alychow** [comment]
@jappyaid we need a level 0 flow diagram for each of our use cases, so we should finish defining those first before we start

**Comment by alychow** [comment]
@jappyaid also, we need to do a level 1 flow diagram for one use case

**Comment by jappyaid** [comment]
ok its chill
should be decently "easy"
